version: '3.9'

services:
  rococo-all-db:
    container_name: rococo-all-db
    image: postgres:15.1
    environment:
      - POSTGRES_MULTIPLE_DATABASES="rococo-auth","rococo-userdata","rococo-country","rococo-museum"
      - PGUSER=postgres
      - POSTGRES_PASSWORD=secret
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres", "-d", "postgres" ]
      interval: 3s
      timeout: 3s
      retries: 5
    expose:
      - "5432"
    networks:
      - test-network
    dns_search: .

  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:7.3.2
    expose:
      - "2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
    networks:
      - test-network
    dns_search: .

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:7.3.2
    expose:
      - "9092"
    depends_on:
      zookeeper:
        condition: service_started
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
    networks:
      - test-network
    dns_search: .

  auth.rococo.dc:
    container_name: auth.rococo.dc
    image: ${PREFIX}/rococo-auth-${PROFILE}:latest
    expose:
      - "9000"
    healthcheck:
      test: "wget --spider http://localhost:9000/actuator/health || exit 1"
      interval: 5s
      timeout: 5s
      retries: 10
    depends_on:
      rococo-all-db:
        condition: service_healthy
      kafka:
        condition: service_started
    networks:
      - test-network
    dns_search: .

  country.rococo.dc:
    container_name: country.rococo.dc
    image: ${PREFIX}/rococo-country-${PROFILE}:latest
    expose:
      - "8091"
      - "8092"
    depends_on:
      rococo-all-db:
        condition: service_healthy
    networks:
      - test-network
    dns_search: .

  gateway.rococo.dc:
    container_name: gateway.rococo.dc
    image: ${PREFIX}/rococo-gateway-${PROFILE}:latest
    expose:
      - "8090"
    depends_on:
      auth.rococo.dc:
        condition: service_healthy
    networks:
      - test-network
    dns_search: .

  museum.rococo.dc:
    container_name: museum.rococo.dc
    image: ${PREFIX}/rococo-museum-${PROFILE}:latest
    expose:
      - "8093"
    depends_on:
      rococo-all-db:
        condition: service_healthy
    networks:
      - test-network
    dns_search: .

  userdata.rococo.dc:
    container_name: userdata.rococo.dc
    image: ${PREFIX}/rococo-userdata-${PROFILE}:latest
    expose:
      - "8089"
    depends_on:
      auth.rococo.dc:
        condition: service_healthy
    networks:
      - test-network
    dns_search: .

  frontend.rococo.dc:
    container_name: frontend.rococo.dc
    image: "${FRONT_IMAGE}"
    expose:
      - "80"
    depends_on:
      gateway.rococo.dc:
        condition: service_started
    networks:
      - test-network
    dns_search: .

  selenoid:
    container_name: selenoid
    image: aerokube/selenoid:1.11.2
    platform: "${ARCH}"
    volumes:
      - ./selenoid:/etc/selenoid
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    command: [ "-conf", "/etc/selenoid/browsers.json", "-limit", "3", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs", "-container-network", "rococo-st5_test-network" ]
    ports:
      - "4444:4444"
    networks:
      - test-network
    dns_search: .

  selenoid-ui:
    container_name: selenoid-ui
    image: aerokube/selenoid-ui:1.10.11
    depends_on:
      - selenoid
    restart: unless-stopped
    ports:
      - "9091:8080"
    command: [ "--selenoid-uri", "http://selenoid:4444" ]
    networks:
      - test-network
    dns_search: .

  rococo-e-2-e:
    container_name: rococo-e-2-e
    image: ${PREFIX}/rococo-e-2-e-tests:latest
    environment:
      - ALLURE_DOCKER_API=${ALLURE_DOCKER_API}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    depends_on:
      frontend.rococo.dc:
        condition: service_started
    volumes:
      - allure-artifacts:/rococo/rococo-e-2-e-tests/build/allure-results/
    networks:
      - test-network
    dns_search: .

  allure:
    container_name: allure
    image: frankescobar/allure-docker-service:2.21.0
    depends_on:
      - rococo-e-2-e
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 3
      KEEP_HISTORY: 1
    ports:
      - "5050:5050"
    networks:
      - test-network
    dns_search: .

  allure-ui:
    container_name: allure-ui
    image: frankescobar/allure-docker-service-ui:7.0.3
    depends_on:
      - allure
    environment:
      ALLURE_DOCKER_PUBLIC_API_URL: "http://localhost:5050"
    ports:
      - "5252:5252"
    networks:
      - test-network
    dns_search: .

volumes:
  allure-artifacts:

networks:
  test-network:
    driver: bridge